# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI_uF8mxWeWOGqLtkad3qDlISAT2y2tH
"""

!pip install onnx onnxruntime

!pip install onnx onnxscript

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
data = load_diabetes()

# Use ONLY first 7 features to match professor style
X = data.data[:, :7]
y = data.target

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Normalize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Tensor conversion
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1,1)

# Model
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(7, 32)
        self.fc2 = nn.Linear(32, 16)
        self.fc3 = nn.Linear(16, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

model = Net()

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Train
for epoch in range(300):
    optimizer.zero_grad()
    out = model(X_train)
    loss = criterion(out, y_train)
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(epoch, loss.item())


model.eval()


torch.onnx.export(
    model,
    torch.randn(1, 7),
    "model.onnx",
    input_names=["input1"],
    output_names=["output1"],
    opset_version=15,
    export_params=True,
    do_constant_folding=True,
    keep_initializers_as_inputs=False
)

import onnx

model = onnx.load("model.onnx")

onnx.save_model(
    model,
    "model.onnx",
    save_as_external_data=False
)

from google.colab import files
files.download("model.onnx")