# -*- coding: utf-8 -*-
"""training ONNX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BLRRVPJOOKXWft8Dj_3vAVQdWG1yuHQ
"""

!pip install onnx onnxruntime

!pip install onnx onnxscript

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
data = load_diabetes()

X = data.data
y = data.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Normalize inputs
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1,1)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1,1)

# Define model
class DiabetesNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(10,32)
        self.fc2 = nn.Linear(32,16)
        self.fc3 = nn.Linear(16,1)

    def forward(self,x):

        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)

        return x

model = DiabetesNet()

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(300):

    optimizer.zero_grad()

    outputs = model(X_train)

    loss = criterion(outputs, y_train)

    loss.backward()

    optimizer.step()

    if epoch % 50 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

# Evaluate model
with torch.no_grad():

    predictions = model(X_test)

    test_loss = criterion(predictions, y_test)

    print("Test MSE:", test_loss.item())

# Export ONNX
model.eval()

dummy_input = torch.randn(1,10)

torch.onnx.export(
    model,
    dummy_input,
    "model.onnx",
    input_names=["input"],
    output_names=["output"],
    opset_version=11,
    export_params=True,
    do_constant_folding=True
)

from google.colab import files
files.download("model.onnx")

